// Atlas project config. The desired state is the whole schema directory — Atlas
// concatenates every *.hcl (one file per resource, generated by togo).
env "local" {
  src = "file://db/atlas/schema"
  url = getenv("DATABASE_URL")
  dev = getenv("DEV_DATABASE_URL")
  migration {
    dir = "file://db/atlas/migrations"
  }
}
