// Code generated by togo. DO NOT EDIT.
package rest

import (
	"github.com/danielgtaylor/huma/v2"

	"github.com/togo-framework/to-go.dev/internal/app"
)

// RegisterRoutes mounts every generated resource's REST routes. Regenerated by
// make:controller / generate; empty until you add a controller.
func RegisterRoutes(api huma.API, a *app.App) {
	_ = a
}
