// Code generated by togo. DO NOT EDIT.
package seeders

import (
	"context"

	"github.com/togo-framework/to-go.dev/internal/app"
)

// SeedAll runs every resource seeder. Regenerated from togo.resources.yaml.
func SeedAll(ctx context.Context, a *app.App) error {
	return nil
}
